AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  DockerTag:
    Type: String
    Default: local-stori-dev

Resources:
  StoriTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: !Sub 'storitestfunction:${DockerTag}' 
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /stori-test
            Method: POST
      Environment:
        Variables:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: "587"
          EMAIL_FROM: ente011@gmail.com
          EMAIL_CODE: "mjjr aekr oikv qclv"
          DB_DRIVER: postgres
          DB_NAME: db_stori
          DB_USER: db_user
          DB_HOST: host.docker.internal
          DB_PORT: "5432"
          DB_PASS: db_pass
    Metadata:
      DockerTag: !Ref DockerTag
      DockerContext: ./stori-test
      Dockerfile: Dockerfile

Outputs:
  StoriTestAPI:
    Description: "API Gateway endpoint URL for Prod environment for Stori Test Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stori-test/"
  StoriTestFunction:
    Description: "Stori Test Lambda Function ARN"
    Value: !GetAtt StortiTestFunction.Arn
  StoriTestFunctionIamRole:
    Description: "Implicit IAM Role created for Stori Test function"
    Value: !GetAtt StoriTestFunctionRole.Arn
